learning_templates/basic_app/urls.py
from django.conf.urls import url,include
from basic_app import views
app_name='basic_app'
urlpatterns=[
            url(r'^relative/$',views.relative,name='relative'),
            url(r'^other/$',views.other,name='other'),

]

learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path
from basic_app import views
from django.conf.urls import url, include

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',views.index,name='index'),
    url(r'^basic_app/', include('basic_app.urls'))

]

learning_templates/basic_app/models.py
from django.db import models

# Create your models here.

learning_templates/basic_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict={'text':'hello world','number':100}
    return render(request, 'basic_app/index.html',context_dict)


def other(request):
    return render(request, 'basic_app/other.html')


def relative(request):
    return render(request, 'basic_app/relative_url_templates.html')

learning_templates/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <!---<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script> ---->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</head>
<body>
<!---<nav class = "navbar navbar-default navbar static-top">
    <div class = "container">
        <ul class = "nav navbar-nav">
            <li> <a class="navbar-brand" href="{%url 'index' %}">Home</a> </li>
            <li> <a class="navbar-link" href="{%url 'basic_app:other' %}">About</a> </li>
            <li> <a class="navbar-link" href="{%url 'admin:index' %}">Admin</a> </li>
        </ul>
    </div>
</nav> --->
<div class="jumbotron">
<div class="mx-auto" style="width: 200px;">
  <div class="p-3 mb-2 bg-dark text-white font-family='Great Vibes',cursive" >Independent Publisher</div>
</div>
</div>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{%url 'index' %}">HOME</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{%url 'basic_app:other' %}">ABOUT ME <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">PHOTOGRAPHY</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{%url 'admin:index' %}">ADMIN</a>
      </li>
    </ul>
  </div>
</nav>
    <div class="container">
        {%block body_block%}
        <---anything outside of this will be inherited--->
        {% endblock %}
    </div>
</body>
</html>

learning_templates/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% block body_block %}
<h1>Welcome to the Home Page</h1>
<p>This is the home page of the portfolio website</p>
{% endblock %}

learning_templates/templates/basic_app/other.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% block body_block %}
<h1>Welcome to the About Page</h1>
<p>This is the About page of the portfolio website</p>
{% endblock %}

learning_templates/templates/basic_app/relative_url_templates.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>welcome to the relative url templates</h1>
<a href="{%url 'basic_app:other'%}">The other page</a>
<a href="{%url 'admin:index'%}">Link to the Admin Page</a>
<a href="{%url 'index'%}">Link to the Index Page</a>

</body>
</html>